import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * General Conference sidebar configuration
 * Auto-generated from the general-conference folder structure
 */
const sidebars: SidebarsConfig = {
  generalConferenceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
