import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * English Learning sidebar configuration
 * Auto-generated from the english-learning folder structure
 */
const sidebars: SidebarsConfig = {
  englishSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
